// runSeoArticle.ts — the BRIDGE that runs the framework `seoArticleAgent` (a SCORELESS agent)
// through the app's REAL intake / seal / payment loop. It reuses the app's exported
// `runInteractiveAgent` (no app -> framework dependency). Unlike the price-range example there is
// NO `produce` hook: a scoreless article is generated by the default LLM producer from the
// collected brief, sealed, and delivered. Run: `npm run example:seo-article`.
//
// Prereqs: register this agent as scoreless once (`cd ../app && npm run register -- --scoreless`)
// and seed the scoreless template (`cd ../app && npm run seed:template -- --scoreless`).

import { fileURLToPath } from "node:url";

import { runInteractiveAgent } from "../../app/src/runtime/runInteractiveAgent.js";
import { seoArticleAgent } from "./seoArticleAgent.js";

// Load the app's .env (this script runs from agent/framework, so the app .env is two dirs up).
function loadAppEnv(): void {
  const loader = (process as { loadEnvFile?: (path?: string) => void }).loadEnvFile;
  if (typeof loader !== "function") return;
  try {
    loader(fileURLToPath(new URL("../../app/.env", import.meta.url)));
  } catch {
    // No .env -- rely on whatever is already in the environment.
  }
}

function parseUser(argv: readonly string[]): string {
  const i = argv.indexOf("--user");
  return i >= 0 && i + 1 < argv.length ? argv[i + 1] : "demo-user";
}

async function main(): Promise<void> {
  loadAppEnv();
  // No produce hook: the default LLM producer writes the article from the collected brief.
  await runInteractiveAgent({
    character: seoArticleAgent.character,
    user: parseUser(process.argv.slice(2)),
  });
}

main().catch((err) => {
  console.error("example:seo-article crashed:", err instanceof Error ? (err.stack ?? err.message) : err);
  process.exit(1);
});
